server:
  port: 8088

logging:
  level:
    '[org.springframework]': INFO
    
spring:
  messages:
    basename: messages
  devtools:
    livereload:
      enabled: true
  security:
    user:
      name: username
      password: passw0rd

    
management:
  endpoints:
    web:
      exposure:
        include: "*"
        
